server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL}  #jdbc:mysql://localhost:3306/application_auth_db
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.instance.prefer-ip-address=true


spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.timeout=60000

logging.level.org.springframework.security: DEBUG

# Health check for probes 

# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info

# Show detailed health (useful for DB/Redis checks)
management.endpoint.health.show-details=always

# Make actuator use the same port as the server
management.server.port=8081
